site_name: Cambridge - CS Group Projects
site_url: https://cambridge-group-projects.github.io/website/
theme:
  name: material
nav:
  - Home: index.md
  - Intellectual Property: Intellectual_property.md
  - Clients:
    - Logistics for Clients: Logistics_for_Clients.md
