site_name: Cambridge - CS Group Projects
site_url: https://https://group-projects.cst.cam.ac.uk/
repo_url: https://github.com/cambridge-group-projects/website/wiki
use_directory_urls:     false
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: custom
    accent: custom
  features:
    - content.action.edit
    - navigation.instant.preview

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: '¶'

plugins:
 - search
 - github-wiki-edit-url
 - ezlinks

static_templates:
 - 404.html

nav:
  - Home: index.md
  - General Information:
    - What makes a good project?: What_makes_a_good_project.md
    - Intellectual Property: Intellectual_property.md
    - Logistics for Clients: Logistics_for_Clients.md
    - Information for DoS: Directors_of_Studies.md
    - Information for Project Coordinators: Coordinators.md
  - Historic Design Briefs:
    - 2025: 2025_list.md
    - 2024: 2024_list.md
    - 2023: 2023_list.md
    - 2022: 2022_list.md
    - 2021: 2021_list.md
    - 2020: 2020_list.md
    - 2019: 2019_list.md
    - 2018: 2018_list.md
    - 2017: 2017_list.md
    - 2016: 2016_list.md
    - 2015: 2015_list.md
    - 2014: 2014_-_final_list_of_design_briefs.md
    - 2013: 2013_-_final_list_of_design_briefs.md
    - 2010: 2010.md
    - 2009: 2009.md
    - 2008: 2008.md
    - 2006: 2006.md

extra_css:
  - stylesheets/extra.css
